name: CI & Deploy (Option A)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install test deps
        run: pip install requests
      - name: Run API tests (non-destructive)
        run: |
          python backend_test_hardened.py             --base-url "${{ secrets.GMB_BASE_URL }}"             --username "${{ secrets.GMB_ADMIN_USERNAME }}"             --password "${{ secrets.GMB_ADMIN_PASSWORD }}"             --json-out ci_results.json
      - name: Upload test artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ci_results.json

  deploy-backend-render:
    needs: api-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy Hook
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "RENDER_DEPLOY_HOOK not set; skipping backend deploy."
          else
            curl -fsSL "${{ secrets.RENDER_DEPLOY_HOOK }}"
          fi

  deploy-frontend-vercel:
    needs: api-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy via Vercel CLI
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          prod: true
