services:
  - type: web
    name: gmb-backend
    env: docker
    plan: free
    region: oregon
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRES_IN
        value: "86400"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: LOG_LEVEL
        value: info
